name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::557062710055:role/GH_Actions_DLHub_Search_Lambda_Deployer
        role-session-name: dlhub-search-deployer
        aws-region: us-east-1

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Upload Globus Search Ingest Lambda
      run: |
         # Install the requirements.
         pip3 install --platform manylinux2010_x86_64 \
                      --use-deprecated=legacy-resolver  \
                      --implementation cp \
                      --python 3.9 \
                      --only-binary=:all: --upgrade \
                      -r requirements.txt -t ./packages
         # Put the requirements into the top level of our deployable zip archive.
         cd packages
         zip -r ../searchlambda.zip *
         # Put the application code into the top level of our deployable zip archive.
         cd ../
         zip -r searchlamdba.zip search_ingest_lambda.py
         # Deploy to Lambda.
         aws lambda update-function-code --function-name DLHubGlobusSearchWriter --zip-file fileb://searchlambda.zip
         # Delete temporary packages directory
         rm -rf packages
